version: "3.9"
services:
  backend:
    build: ./backend
    container_name: consent-backend
    ports:
      - "8000:8000"
    volumes:
      - backend_db:/app/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend/consent-frontend
      dockerfile: Dockerfile
    container_name: consent-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  backend_db:
