version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: consent-backend
    ports:
      - "8000:8000"
    networks:
      - consent-net

  frontend:
    build:
      context: ./frontend/consent-frontend
    container_name: consent-frontend
    ports:
      - "5173:80"
    networks:
      - consent-net

networks:
  consent-net:
    driver: bridge
